substitutions:
  device_name: front-room-display-2
  friendly_name: Front Room Display 2
  device_description: Front Room Display 2
  room: Front Room

esp8266:
  board: esp01_1m
  restore_from_flash: true

packages:
  minimal: !include /root/config/packages/0_general/minimal.yaml
  basic: !include /root/config/packages/0_general/basic.yaml
  arduino: !include /root/config/packages/0_general/arduino.yaml

    
output:
  - platform: esp8266_pwm
    id: pwm_output
    # frequency: 1000 Hz
    pin: GPIO12 

light:
  - platform: monochromatic
    name: "Display Cabinet 2 Light"
    default_transition_length: 1s
    output: pwm_output
