substitutions:
  device_name: kitchen-counter-light
  friendly_name: Kitchen Counter Light
  device_description: Kitchen Counter Light
  room: Kitchen
  
esp8266:
  board: esp01_1m
  restore_from_flash: true

packages:
  minimal: !include /root/config/packages/0_general/minimal.yaml
  basic: !include /root/config/packages/0_general/basic.yaml
  arduino: !include /root/config/packages/0_general/arduino.yaml

    
output:
  - platform: esp8266_pwm
    id: pwm_output
    # frequency: 1000 Hz
    pin: GPIO12 

light:
  - platform: monochromatic
    name: "Counter Light"
    default_transition_length: 1s
    output: pwm_output
