substitutions:
  device_name: house-bluetooth
  friendly_name: House Bluetooth
  device_description:  House Bluetooth in Laundry
  room: House

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  minimal: !include /root/config/packages/0_general/minimal_eth.yaml
  basic: !include /root/config/packages/0_general/basic_eth.yaml
  arduino: !include /root/config/packages/0_general/arduino_eth.yaml
  bt_proxy: !include /root/config/packages/0_general/bt_proxy.yaml