substitutions:
  devicename: house-bluetooth
  friendly_name: House Bluetooth
  device_description:  House Bluetooth in Laundry
  
esphome:
  name: $devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

#enable ethernet
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

#enable web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryptionkey

# Enable OTA
ota:
  - platform: esphome
    password: !secret ESPHomeOTA

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic