substitutions:
  device_name: living-room-ac
  friendly_name: Living Room AC
  device_description: Living Room AC
  room: Living Room
  
external_components:
  - source: github://GrKoR/esphome_aux_ac_component
    components: [ aux_ac ]
    refresh: 0s

esp32:
  board: esp32dev
  framework:

    type: arduino
packages:
  minimal: !include /root/config/packages/0_general/minimal.yaml
  basic: !include /root/config/packages/0_general/basic.yaml
  bt_proxy: !include /root/config/packages/0_general/bt_proxy.yaml
  
# UART0 configuration for AUX air conditioner communication
uart:
  id: ac_uart_bus
  # ATTENTION! Use GPIO4 (D2) and GPIO5 (D1) as the TX and RX for NodeMCU-like boards!
  tx_pin: GPIO22
  rx_pin: GPIO21
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1

climate:
  - platform: aux_ac
    name: Living AC
    id: aux_id
    uart_id: ac_uart_bus
    period: 7s
    show_action: true
    display_inverted: true
    optimistic: true
    indoor_temperature:
      name: Living AC Indoor Temperature
      id: Living_AC_indoor_temp
      internal: false
    display_state:
      name: Living AC Display State
      id: Living_AC_display_state
      internal: false
    outdoor_temperature:
      name: Living AC Outdoor Temperature
      id: Living_AC_outdoor_temp
      internal: false
    outbound_temperature:
      name: Living AC Coolant Outbound Temperature
      id: Living_AC_outbound_temp
      internal: false
    inbound_temperature:
      name: Living AC Coolant Inbound Temperature
      id: Living_AC_inbound_temp
      internal: false
    compressor_temperature:
      name: Living AC Compressor Temperature
      id: Living_AC_strange_temp
      internal: false
    defrost_state:
      name: Living AC Defrost State
      id: Living_AC_defrost_state
      internal: false
    inverter_power:
      name: Living AC Invertor Power
      id: Living_AC_inverter_power
      internal: false
    preset_reporter:
      name: Living AC Preset Reporter
      id: Living_AC_preset_reporter
      internal: false
    vlouver_state:
      name: Living AC VLouvers State
      id: Living_AC_vlouver_state
      internal: false
    visual:
      min_temperature: 16
      max_temperature: 32
      temperature_step: 0.5
    supported_modes:
      - HEAT_COOL
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    custom_fan_modes:
      - MUTE
      - TURBO
    supported_presets:
      - SLEEP
    custom_presets:
      - CLEAN
      - HEALTH
      - ANTIFUNGUS
    supported_swing_modes:
      - VERTICAL
      - HORIZONTAL
      - BOTH


sensor:
  # just wifi signal strength for debug purpose only
  - platform: wifi_signal
    name: Living AC WiFi Signal
    update_interval: 30s
    unit_of_measurement: "dBm"
    accuracy_decimals: 0

  - platform: uptime
    name: Living AC Uptime Sensor

switch:
  - platform: template
    name: Living AC Display
    lambda: |-
      if (id(Living_AC_display_state).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - aux_ac.display_on: aux_id
    turn_off_action:
      - aux_ac.display_off: aux_id

button:
  - platform: template
    name: Living AC VLouver Stop
    icon: "mdi:circle-small"
    on_press:
      - aux_ac.vlouver_stop: aux_id
    
  - platform: template
    name: Living AC VLouver Swing
    icon: "mdi:pan-vertical"
    on_press:
      - aux_ac.vlouver_swing: aux_id
    
  - platform: template
    name: Living AC VLouver Top
    icon: "mdi:pan-up"
    on_press:
      - aux_ac.vlouver_top: aux_id
    
  - platform: template
    name: Living AC VLouver Middle Above
    icon: "mdi:pan-top-left"
    on_press:
      - aux_ac.vlouver_middle_above: aux_id
    
  - platform: template
    name: Living AC VLouver Middle
    icon: "mdi:pan-left"
    on_press:
      - aux_ac.vlouver_middle: aux_id
    
  - platform: template
    name: Living AC VLouver Middle Below
    icon: "mdi:pan-bottom-left"
    on_press:
      - aux_ac.vlouver_middle_below: aux_id
    
  - platform: template
    name: Living AC VLouver Bottom
    icon: "mdi:pan-down"
    on_press:
      - aux_ac.vlouver_bottom: aux_id


number:
  - platform: template
    name: Living AC Vertical Louvers
    id: Living_AC_vlouver
    icon: "mdi:circle-small"
    mode: "slider"
    min_value: 0
    max_value: 6
    step: 1
    update_interval: 2s
    lambda: |-
      return id(Living_AC_vlouver_state).state;
    set_action:
      then:
        - aux_ac.vlouver_set:
            id: aux_id
            position: !lambda "return x;"

  - platform: template
    name: Living AC Power Limit
    id: Living_AC_power_limit
    icon: "mdi:battery-unknown"
    mode: "slider"
    min_value: 30
    max_value: 100
    step: 1
    set_action:
      then:
        - lambda: !lambda "id(aux_id).powerLimitationOnSequence( x );"