substitutions:
  devicename: master-bathroom-lights
  friendly_name: master-bathroom-lights
  device_description: Master Bathroom Lights
  
esphome:
  name: $devicename
  comment: ${device_description}

esp8266:
  board: esp01_1m
  restore_from_flash: true

wifi:
  ssid: !secret SSID_IoT
  password: !secret PASSWORD_IoT
  power_save_mode: none

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master Bathroom Lights Fallback"
    password: !secret PASSWORD_fallback

captive_portal:

# Enable logging
logger:

# Enable web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryptionkey

# Enable OTA
ota:
  - platform: esphome
    password: !secret ESPHomeOTA

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12 
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
        - light.toggle: light_1

  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: True
    id: button_2
    on_press:
        - light.toggle: light_2
        
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    id: button_3
    on_press:
        - light.toggle: light_3

output:
  - platform: gpio
    pin: GPIO13
    id: relay_1

  - platform: gpio
    pin: GPIO04
    id: relay_2
    
  - platform: gpio
    pin: GPIO15
    id: relay_3
    
light:
  - platform: binary
    name: "Master Bathroom Light 1"
    id: light_1
    output: relay_1

  - platform: binary
    name: "Master Bathroom Fan"
    id: light_2
    output: relay_2
    
  - platform: binary
    name: "Master Bathroom Light 2"
    id: light_3
    output: relay_3

status_led:
  pin:
    number: GPIO00
    inverted: yes