substitutions:
  device_name: master-bathroom-lights
  friendly_name: master-bathroom-lights
  device_description: Master Bathroom Lights
  room: Master Bathroom
  
esp8266:
  board: esp01_1m
  restore_from_flash: true

packages:
  minimal: !include /root/config/packages/0_general/minimal.yaml
  basic: !include /root/config/packages/0_general/basic.yaml
  arduino: !include /root/config/packages/0_general/arduino.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12 
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
        - light.toggle: light_1

  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: True
    id: button_2
    on_press:
        - light.toggle: light_2
        
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    id: button_3
    on_press:
        - light.toggle: light_3

output:
  - platform: gpio
    pin: GPIO13
    id: relay_1

  - platform: gpio
    pin: GPIO04
    id: relay_2
    
  - platform: gpio
    pin: GPIO15
    id: relay_3
    
light:
  - platform: binary
    name: "Master Bathroom Light 1"
    id: light_1
    output: relay_1

  - platform: binary
    name: "Master Bathroom Fan"
    id: light_2
    output: relay_2
    
  - platform: binary
    name: "Master Bathroom Light 2"
    id: light_3
    output: relay_3

status_led:
  pin:
    number: GPIO00
    inverted: yes