substitutions:
  device_name: mmwave-01
  friendly_name: mmwave 1
  device_description: mmwave-01
  room: Test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

packages:
  minimal: !include /root/config/packages/0_general/minimal.yaml
  basic: !include /root/config/packages/0_general/basic.yaml
  arduino: !include /root/config/packages/0_general/arduino.yaml

    