substitutions:
  device_name: mmwave-02
  friendly_name: mmwave 2
  device_description: mmwave-02
  room: Test

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  minimal: !include /root/config/packages/0_general/minimal.yaml
  basic: !include /root/config/packages/0_general/basic.yaml
  arduino: !include /root/config/packages/0_general/arduino.yaml
  bt_proxy: !include /root/config/packages/0_general/bt_proxy.yaml