substitutions:
  device_name: stewart-desk-switchs
  friendly_name: Stewart Desk
  device_description: Stewart Desk
  room: "Stewart Desk"

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  minimal: !include /root/config/packages/0_general/minimal.yaml
  basic: !include /root/config/packages/0_general/basic.yaml
  arduino: !include /root/config/packages/0_general/arduino.yaml

#dallas:
#  - pin: GPIO14
      
#  - platform: dallas
#    address: 0xD703099779169828
#    name: "Shed03 Temperature"
    
binary_sensor:
#Button 1 
  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
      - switch.toggle: relay_1
      
#Button 2 
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_2
    on_press:
      - switch.toggle: relay_2
      
#Button 1 
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    id: button_3
    on_press:
      - switch.toggle: relay_3
      
#Button 2 
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    id: button_4
    on_press:
      - switch.toggle: relay_4
      
switch:
#Relay 1
  - platform: gpio
    name: "Stewart Screens"
    pin: GPIO5
    id: relay_1
    
#Relay 2   
  - platform: gpio
    name: "Hot Air Reflow"
    pin: GPIO12
    id: relay_2
    
#Relay 3
  - platform: gpio
    name: "Solder Station"
    pin: GPIO13
    id: relay_3
    
#Relay 4
  - platform: gpio
    name: "Test PowerSupply"
    pin: GPIO15
    id: relay_4