substitutions:
  devicename: stewart-desk-switchs
  friendly_name: Stewart Desk
  device_description: Stewart Desk
  
esphome:
  name: $devicename
  comment: ${device_description}

esp8266:
  board: esp01_1m
  restore_from_flash: true
  
wifi:
  ssid: !secret SSID_IoT
  password: !secret PASSWORD_IoT
  power_save_mode: none

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret PASSWORD_fallback

captive_portal:

# Enable logging
logger:

# Enable web server
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryptionkey

# Enable OTA
ota:
  - platform: esphome
    password: !secret ESPHomeOTA

#dallas:
#  - pin: GPIO14
      
#  - platform: dallas
#    address: 0xD703099779169828
#    name: "Shed03 Temperature"
    
binary_sensor:
#Button 1 
  - platform: gpio
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: True
    id: button_1
    on_press:
      - switch.toggle: relay_1
      
#Button 2 
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button_2
    on_press:
      - switch.toggle: relay_2
      
#Button 1 
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    id: button_3
    on_press:
      - switch.toggle: relay_3
      
#Button 2 
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    id: button_4
    on_press:
      - switch.toggle: relay_4
      
switch:
#Relay 1
  - platform: gpio
    name: "Stewart Screens"
    pin: GPIO5
    id: relay_1
    
#Relay 2   
  - platform: gpio
    name: "Hot Air Reflow"
    pin: GPIO12
    id: relay_2
    
#Relay 3
  - platform: gpio
    name: "Solder Station"
    pin: GPIO13
    id: relay_3
    
#Relay 4
  - platform: gpio
    name: "Test PowerSupply"
    pin: GPIO15
    id: relay_4