esphome:
  name: shed-presence-sensor
  friendly_name: shed-presence-sensor

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "QsMaclP+Q8Cv2tvCoLNBUM6BBCQN05DH76O/Ff0g9qQ="

ota:
  - platform: esphome
    password: "961f5f43758f0e3ee718933ce4dbfe36"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Shed-Presence-Sensor"
    password: "IdVErji8hXuT"

captive_portal:
    