time:
  # Sync time with HA
  - platform: homeassistant
    id: time_homeassistant
    timezone: "Australia/Melbourne"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

# Sensors with general information.
sensor:
  # Uptime sensor (internal only).
  - platform: uptime
    id: sensor_uptime
  # Uptime timestamp
  - platform: template
    id: sensor_uptime_timestamp
    name: "${friendly_name} Uptime"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state
      );
      return timestamp;
    entity_category: diagnostic

button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: diagnostic

  - platform: safe_mode
    name: "${friendly_name} Safe Mode"
    internal: false
    entity_category: diagnostic
