time:
  # Sync time with HA
  - platform: homeassistant
    id: time_homeassistant
    timezone: "Australia/Melbourne"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

text_sensor:
  # IP Address & SSID
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: mdi:wifi
      entity_category: diagnostic

  - platform: template
    name: "${friendly_name} Uptime"
    id: sensor_uptime_timestamp
    entity_category: diagnostic
    lambda: |-
      int seconds = (id(sensor_uptime).state);
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds / 60;
      seconds = seconds % 60;
      if (days > 3650) {
        return {"Starting up"};
      } else if (days) {
        return {(String(days) + "d " + String(hours) + "h " + String(minutes) + "m " + String(seconds) + "s").c_str()};
      } else if (hours) {
        return {(String(hours) + "h " + String(minutes) + "m " + String(seconds) + "s").c_str()};
      } else if (minutes) {
        return {(String(minutes) + "m " + String(seconds) + "s").c_str()};
      } else {
        return {(String(seconds) + "s").c_str()};
      }
    icon: mdi:clock-start


# Sensors with general information.
sensor:
  # Uptime sensor (internal only).
  - platform: uptime
    id: sensor_uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    icon: mdi:wifi-strength-2
    update_interval: 60s

button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config

  - platform: safe_mode
    name: "${friendly_name} Safe Mode"
    internal: false
    entity_category: config

binary_sensor:
  - platform: status
    name: "${friendly_name}_status"

